### ISSUE TITLE
Instancing of nested references doesn't work

### ISSUE THREAD

**Issue by stephenrblair** [Autodesk/arnold-usd#1145]
**Describe the bug**
Instances of references, and point instancing of those instances, do not work.

User says:
We have stumbled into some issues when rendering USD files with nested instances with Arnold. The original issue comes with geometry exported from Clarisse to USD, where we started to find that a big amount of instances were missing. We've managed to create a repro scene that has the same issues as our production scenes. 

In the .zip file you'll find the usd file along with several images of the result of rendering it with Arnold. Strangely enough, this scenes gives no problem when rendering it via Solaris.

**To Reproduce**
1. Download and extract the attached zip
[autodesk_bug_report.zip](https://github.com/Autodesk/arnold-usd/files/8626233/autodesk_bug_report.zip)

2. kick usd_test_stage.usda

With the latest Arnold 7.1.x.0 available to me on 05 April 2022 I get this in the log. See the screenshot below for the render.
`00:00:04   197MB WARNING |  [ginstance] : trying to clone a NULL object
00:00:04   197MB WARNING |  [ginstance] : trying to clone a NULL object
00:00:04   197MB WARNING |  [ginstance] : trying to clone a NULL object
00:00:04   197MB WARNING |  [ginstance] /root/instances/geo/root/rock_scatter/Prototypes/root/rock_01: trying to clone a NULL object`

**Expected behavior**
Instances (the rocks) should show up in the renders.

**Screenshots**
With 7.1.1.x
![image (1)](https://user-images.githubusercontent.com/98059981/166803805-0579079b-02b2-446a-b698-2048a7068d80.png)

**Used Software Versions**
 - Arnold: 6.2, 7.0, 7.1, 7.1.x
 

**Additional context**

**Comment by sebastienblor** [comment]
The issue happens because we have an instanceable reference pointing to another instanceable reference. 
In the attached scene, we have for example a point instancer `/root/pointinstance_instance/instancer/Prototypes/root/instances/geo/root/rock_scatter` which prototype under its hierarchy is  `Prototypes/root/rock_01`.  This primitive is defined as a reference like this :
` append references = </root/instances/geo/root/rock_01>
`

But the primitive referenced above is itself a reference to another file, defined as   
`prepend references = @./usd_sources/geometries.usda@</root/geo/stamp/rock_01>
`

and that's what is not properly supported here. If we changed the first primitive to point directly to the last one, it would work fine. It would mean to replace line 123 by 
`append references = @./usd_sources/geometries.usda@</root/geo/stamp/rock_01>`

**Comment by sebastienblor** [comment]
This issue was fixed with #1187 , so we can close this ticket
