### ISSUE TITLE
Portal Lights no longer working in Arnold Hydra Delegate in USDView (possible Arnold regression)

### ISSUE THREAD

**Issue by ansuter** [Autodesk/arnold-usd#1229]
**Describe the bug**
Portal lights no longer work when rendering via Arnold 7.1.2.1 in usdview

**To Reproduce**
Export via Maya 2022 (mtoa 4.2.4) or Maya 2023 (mtoa 5.1.3.1). You'll see the appropriate portal light attributes that direct the skydome light appropriately.

Then using usdview using arnold  6.2.1.1, you'll see it uses the lights correctly.

![image](https://user-images.githubusercontent.com/16786318/180842631-fb2d10ac-62fe-4af3-bc48-a6f639b555bc.png)
![image](https://user-images.githubusercontent.com/16786318/180842741-f9a3ff90-3c3e-411e-97a7-c4fc8e655f94.png)

Then load it up using usdview using arnold 7.1.2.1.  You'll see the lights are not correct.

![image](https://user-images.githubusercontent.com/16786318/180847334-bdd6942d-b31f-4b13-8052-5e305d11de89.png)

I also tried exporting via mtoa 5.1.3.1 and get the same issue.

I attached a scene that works for me with earlier versions of arnold.

**Expected behavior**
Portal lights should work.

**Used Software Versions**
 - Arnold: [e.g. 5.4.0.2] mtoa 4.2.4 (working), mtoa 5.1.3.1 (not working)
 - USD: [e.g. 0.19.11] USD 20.08 (working), USD 21.11 (not working)
 - Compiler: [e.g. GCC 4.8.5]
 - OS: [e.g. MacOS 10.15] Windows
 - Any 3rd-party app: [e.g. Katana-3.2]

**Additional context**
[light-portals-2022.zip](https://github.com/Autodesk/arnold-usd/files/9183910/light-portals-2022.zip)

**Comment by cpichard** [comment]
Hi @ansuter , 
this issue is similar to #1209 where, starting from usd 21.11, the scene delegate is behaving differently than it did in the previous versions. 
We should release a patch very soon, and I double checked it was fixing your issue, in usdview the portal light are correctly rendered.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/300243/186206277-e74f70ce-3dab-45bd-b116-92639c1fd957.png">

Thanks for the detailed issue.
Cyril
