### ISSUE TITLE
Setting up Arnold to work within Solaris is so confusing.

### ISSUE THREAD

**Issue by Qulzoom** [Autodesk/arnold-usd#129]
Help please, I'm so clueless as to building and installing instructions. I have Arnold 6, H18.0.287. Repository downloaded. Why is setting it all up so complex?

**Comment by sirpalee** [comment]
Hey, @Qulzoom .

If you want to use this version, instead of the one bundled with HtoA, you need to look at the [documentation](https://github.com/Autodesk/arnold-usd/blob/master/docs/building.md). If you have your environment already configured to compile plugins for Houdini 18 (and follow their build instructions), you can find example build configurations at the end of the documentation for all 3 platforms for standard Houdini 18 installations.

I'm closing this ticket as this is a documented process.
