### ISSUE TITLE
Boost discovery broken when using CMake build

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#1571]
**Describe the bug**

It looks like https://github.com/Autodesk/arnold-usd/commit/bcc07c8b broke the ability of the CMake build to properly find Boost, resulting in a failure to build anything.

I don't really understand why (yet), but the issue seems to be fixed by removing the `PATHS ${USD_LOCATION}` option from these `find_package` commands https://github.com/Autodesk/arnold-usd/blob/master/CMakeLists.txt#L57-L63

**CMake options:**
```
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_EXE_LINKER_FLAGS=-Wl,--enable-new-dtags
        -D CMAKE_SHARED_LINKER_FLAGS=-Wl,--enable-new-dtags
        -D CMAKE_CXX_STANDARD=14
        -D CMAKE_CXX_EXTENSIONS=OFF
        -D CMAKE_INSTALL_RPATH_USE_LINK_PATH=ON

        -D USD_LOCATION=</path/to/USD_root>
        -D USD_LIB_PREFIX=libluma
        -D BUILD_DISABLE_CXX11_ABI=ON
        -D BUILD_SHARED_LIBS=ON

        -D BUILD_SCHEMAS=ON
        -D BUILD_PROCEDURAL=ON
        -D BUILD_RENDER_DELEGATE=OFF
        -D BUILD_USD_IMAGING_PLUGIN=OFF
        -D BUILD_NDR_PLUGIN=OFF
        -D BUILD_USD_WRITER=OFF
        -D BUILD_DOCS=OFF
        src
```

**Used Software Versions**
 - Arnold: 7.1.4.4 / 7.2.2.0
 - USD: 0.22.05
 - Boost: 1.70.0
     - Boost is installed in a separate directory tree from USD.
 - Compiler: GCC 6.3.1
 - OS: CentOS 7.8

**Comment by nrusch** [comment]
I should also mention that I initially started from the `fix-7.2.2` branch and bisected between there and the `Arnold-7.1.4.0` tag to isolate this.

**Comment by cpichard** [comment]
Hi @nrusch , is your boost installed within the usd include dir ? or does it live in a different location ?

**Comment by nrusch** [comment]
Hi @cpichard, I mentioned this in my ticket, but Boost is installed in a separate directory tree from USD.

**Comment by cpichard** [comment]
Hi @nrusch , 
I am currently refactoring the cmake build and want to address your issue in the process.
I have a question for you: USD comes with a cmake configuration files, pxrConfig.cmake and pxrTargets.cmake, which normally contains the list of its dependencies like boost, tbb, python, etc. Having the dependencies filled there would simplify the configuration of the build as you have only to tell cmake where USD and ARNOLD are for a basic setup, the dependencies will be picked up.

Are those files present in your environment ? if so do they contain the correct paths ?

Thanks !

**Comment by cpichard** [comment]
also, would you be able to copy the error you get ? 
Thanks,

**Comment by nrusch** [comment]
Hi @cpichard , thanks for taking a look at this.

We do have `pxrConfig.cmake` and `pxrTargets.cmake` in our USD installations, but in general we don't rely on them for our own internal USD plugins/extensions, as we've had issues with them in the past.

Even if they *would* work here, I don't really think the `arnold-usd` build process should depend on them either, since it limits the number of different environments in which the project can be easily built. For example, because it contains absolute paths to dependencies, there is no possibility of reorganizing your dependencies on disk if you're relying on it.

CMake has a fairly robust module for finding Boost already, so if it were me I would be inclined to start with a simple fix.

**Comment by cpichard** [comment]
Hi @nrusch 

Thanks for the reply !
I'd like to simplify the cmake build, as arnold-usd only needs arnold and usd, and all the libraries we have to add are usd dependencies. We have to maintain a logic in the build code for all the usd build configurations, this is not great. Also the person who compiles arnold-usd needs to make sure he chooses the correct dependencies, meaning the one that were used for building USD, he has to keep track of them, otherwise the build or the runtime can fail. FindBoost is great at finding boost, but it won't know which one was used for usd when you have multiple version installed. I have seen people failing to compile arnold-usd because of that, and it shouldn't happen. In larger studios it's more organised, and probably less of an issue. I understand the need of being able to tweak the build with custom folder location, I think we should keep that as well, like it is now.
But cmake now provides a way to avoid those issues by creating "config" files and we could provide a simple way to compile arnold-usd with usd and the common dccs. As you said pxrConfig/pxrTarget could be improved such that the usd folder can be relocatable.

This obviously is unrelated to your issue here, but it's great to see someone using the cmake build so I'd love to discuss it further, to make sure the new version will work well in your studio. 

Cheers
