### ISSUE TITLE
Support the Hydra point instancer

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#18]
Support the Hydra point instancer for primitives.

Initial support was already added for instancing meshes see [render_delegate/instancer.cpp](https://github.com/Autodesk/arnold-usd/blob/36c113c3d331707b9b68931b32e6d4f018ccb227/render_delegate/instancer.cpp) and related files.

A few features are still missing:
- add support for instancing volumes
- calculating transformation motion blur for instance matrices

We can use [hdEmbree/instancer.cpp](https://github.com/PixarAnimationStudios/USD/blob/4b1162957b2ad219e1635c81de8343be490e41fc/pxr/imaging/plugin/hdEmbree/instancer.cpp) as an example implementation.

**Comment by sirpalee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Render Delegate] Support the point instancer](https://trello.com/c/6pMmUUaI/30-render-delegate-support-the-point-instancer)

**Comment by nrusch** [comment]
As part of the improvements to instancing, I think the render delegate needs to treat the Rprim that is being instanced as if it is not part of the scene, instead of rendering it. This would match the behavior of Embree and Prman delegates.

Right now, if I create an instancer with 8 instances and a single mesh prototype, I get the 8 instances *plus* the original prototype in the render.

This may mean continuing to translate the prototype but making it invisible in Arnold, or generating `numInstances - 1`  `ginstance` nodes and using the prototype for the last one (with the transform of the final instance) The second approach seems nicer and more Arnold-like, but would require the prototype's transform to be factored into the computation of the instance matrices as well.

**Comment by sirpalee** [comment]
@nrusch found an issue with updating transformation matrices for the point instancer and created a solution in #69
