### ISSUE TITLE
Material networks creation in 7.2.4 is slower than before

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1812]
**Describe the bug**
Since version 7.2.4 the creation of material networks is slower than it was in 7.2.3, the time can be multiplied by an order of magnitude. This happens only in the hydra render delegate.

**To Reproduce**
1. Install 7.2.3.x and 7.2.4.x 
2. Use a profiler and render in a hydra enabled application both version

**Comment by BigRoy** [comment]
Just linking this Autodesk forum thread: https://forums.autodesk.com/t5/arnold-for-houdini-forum/htoa-solaris-slow-quot-restart-render-quot-materialx/td-p/12520588

Hoping that the fix for this issue solves that. That's over 30 seconds scene creation time for a relatively simple scene of a single character in a lookdev kit background.
