### ISSUE TITLE
husk should abort render when the arnold license is not found and ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is set

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1950]
**Describe the feature you'd like**
When ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is set, the render will abort if the license is not found. However in husk, the render aborts but husk will write black frames and not return any errors. We want to make sure that when the license is not found and ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is set, husk does not write any frames.

**Comment by xsisupport** [comment]
If I'm batch rendering elsewhere with Arnold (kick, mayabatch, sick), I don't need to set ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL  to abort on license fail. Arnold does it automatically for batch renders.

Is ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL required for husk because husk doesn't know whether it's a batch or interactive render?

**Comment by cpichard** [comment]
Hi, ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is required for husk as we have to abort before the creation of the render delegate, so before reading any file and the options (abort on licence) in the ass file. We did that to be able to run the hydra tests even if the license isn't found. We could change it if setting ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL turns out to be a burden.
