### ISSUE TITLE
[render delegate] Dirtying existing primvars does not propagate changes to Arnold

### ISSUE THREAD

**Issue by nrusch** [Autodesk/arnold-usd#3]
Currently, the functions for pushing primvar data to Arnold nodes will return early if a user parameter cannot be declared. This prevents dirty primvars from propagating to Arnold after they are initially declared.

**Comment by sirpalee** [comment]
This happens because of [render_delegate/utils.cpp:74](https://github.com/Autodesk/arnold-usd/blob/master/render_delegate/utils.cpp#L74) . We need to extend the function to check for existing user attributes. If the type changes, we need to use AiNodeResetParameter on the user parameter and recreate it. The function still has to return false in case AiNodeDeclare fails (like the user attribute name matches a built-in parameter).

**Comment by kikou** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Render Delegate] Dirtying existing primvars does not propagate changes to Arnold](https://trello.com/c/rpEci8Xi/95-render-delegate-dirtying-existing-primvars-does-not-propagate-changes-to-arnold)
