### ISSUE TITLE
Support ramps with linked colors

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#375]
**Describe the bug**
Arnold supports linking some ramps colos / positions to other shaders, but this isn't currently supported in the procedural and writer.

We need to decide how this could be written in a usd file

**Comment by sirpalee** [comment]
At Luma we created additional parameters that the reader/writer codes could handle. We prefixed the element numbers with `i`, that was similar to what KtoA/Katana used to encode array element connections.

Connect to the first element of an array `inputs:arr:i0`
Connect to the third element of an array `inputs:arr:i2`
Connect to the b component of the second element of an array `inputs:arr:i2.b`
Connect to the g component of a single color `inputs:col:g`

I'm not sure what's going to happen when we open this in usdview/hydra, because that's using the Sdr to query the available parameter names.
