### ISSUE TITLE
Changing material rebuilds the shapes in Solaris

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#474]
**Describe the bug**
When changing material properties in Solaris, the shapes are synced again with all their parameters dirtied.

**To Reproduce**
1. Create a heavy geometry in Solaris (or a simple geometry with heavy subdivision)
2. Assign a material to it
3. Change any of the material parameters
4. Observe the delay as the render delegate rebuilds the mesh

**Expected behavior**
Material changes should restart the render almost instantly.

**Used Software Versions**
 - Arnold: 6.0.3.1
 - USD: 19.11
 - Compiler: GCC 6.3.1
 - OS: CentOS 7 and Windows 10
 - Any 3rd-party app: Hoduini-18.0.499

**Additional context**
After the initial investigation, it looks like the shapes are receiving all dirty sync and the render delegate is doing what it's instructed to do.

**Comment by sirpalee** [comment]
This was reported to SideFX and we are still waiting for a reply. Marking the ticket as blocked and removing it from the sprint.

**Comment by sirpalee** [comment]
We got confirmation that fixes for [https://github.com/PixarAnimationStudios/USD/issues/1250](USD 1250) solves the issue. I'm going to move the ticket to low priority because there isn't much we could reasonably due.

**Comment by BigRoy** [comment]
I assume this issue was solved by the fix for [USD 1250](https://github.com/https://github.com/PixarAnimationStudios/OpenUSD/issues/1250) being implemented? Or is that there still something present currently in Arnold-USD for which we should keep this open to track certain optimization possibilities?

---

With Houdini 20.0.547 and Htoa 6.2.5.0 I'm mostly noticing if I go to another frame it restarts the progressive quickly (in scene only geometry changes in position) that the initial sampling is very slow. Then if I move the viewport camera around a bit it remains just as slow and the progression in the progresive rendering is much slower. But then if I 'wait' for a bit as the progression has come along nicely _then_ if I move the camera round suddenly the progression for the new camera position is very rapid. Any idea why it might be slow initially on a new frame?

**Comment by cpichard** [comment]
Hi @BigRoy , I have double checked that when we changed the materials parameter the shapes are not synced again, so all good for this very issue. However, as you mentioned in your last comment and in the forum, I found a bug where the camera node was recreated when there was a change of camera parameter, which in turn forced the resync of the scene which could be very slow on big scene. This was the main cause of the slowdown. There is a PR ready to be merged and land in the next versions of arnold-usd https://github.com/Autodesk/arnold-usd/pull/1855.
Thanks for the investigation, that was really useful.
