### ISSUE TITLE
arnold_to_usd SetScope and SetMask

### ISSUE THREAD

**Issue by kreppene** [Autodesk/arnold-usd#548]
**Describe the feature you'd like**
It would be nice if we could set the scope and mask from the command-line tool

**Describe the solution you'd like**
The command-line interface could look something like this

-i "myfile.ass"               (inpout ass file)
-o "myfile.usd"             (output usd file)
-p "/Root/RootOffset" (parent scope)
-m 24                           (mask)

We already got a way to export from arnold to usd inside mtoa, but the commandline tool is realy usefull also, 
so i think a command-line interface like the solution described above could be relay useful

**Comment by sebastienblor** [comment]
Hi Raymond, this command arnold_to_usd will soon end up being dropped, because last year arnold added support for usd as a scene format.

This means that you can run `kick scene.ass -resave scene.usd`  to convert an arnold scene to usd, or the other way around, or even just kick a usd file. So there's no longer a point in having a dedicated command line, that could behave in a slightly different way. 
What we're missing though in the existing "kick -resave"  workflow, is to be able to pass custom arguments like the ones you're requesting. We're creating an arnold core ticket to add support for that, and we'll probably end up dropping the `arnold_to_usd` command, that is currently not used nor tested on our side.

**Comment by sebastienblor** [comment]
Hi @kreppene , before we deprecate arnold_to_usd, I wanted to provide you with a simple python script that does what you'd expect. The script uses the arnold python module, it loads a .ass file and then calls AiSceneWrite with a usd filename. This is enough to convert the ass file to usd.
In order to pass it some parameters for the conversion, you can create a paramValueMap, and set "mask" and "scope" that will be taken into account during the translation. We have another parameter, a boolean "allAttributes" that will write all attributes even if their value is left to default.

Here's the snippet, please let me know if you need more info

```
import arnold as ai
ai.AiBegin()
ai.AiSceneLoad(None, "C:/test.ass", None)
params = ai.AiParamValueMap()
ai.AiParamValueMapSetInt(params, 'mask', ai.AI_NODE_SHADER);
ai.AiParamValueMapSetStr(params, 'scope', 'test');
ai.AiSceneWrite(None, 'C:/test.usda', params);
ai.AiParamValueMapDestroy(params);
ai.AiEnd()
```
