### ISSUE TITLE
UVs not read from facevarying primvar if indexes are not present

### ISSUE THREAD

**Issue by compso** [Autodesk/arnold-usd#621]
**Describe the bug**
There is a regression in the procedural in 6.0.3.1 where it will not load uv data if the object's uv data is a facevarying primvar but there are no indices present

**To Reproduce**
1. load attached USD file and translate to .ass
2. see the uvlist is not created in 6.0.3.1

**Expected behavior**
the uvs should be read and produce uvidx and uvlist

**Screenshots**

**Used Software Versions**
 - Arnold: 6.0.3.1+
 - OS: [e.g. MacOS 10.15]
 - Any 3rd-party app:Maya 2020, Houdini 18.5

**Comment by compso** [comment]
Attached is the example usd file to replicate the issue

[Char_Female_01_color.zip](https://github.com/Autodesk/arnold-usd/files/5678712/Char_Female_01_color.zip)

**Comment by sirpalee** [comment]
I looked into the problem and found the reason why the uvlist is not set.

When the procedural encounters a primvar without indices, it's using the primvar value to generate a sequence of indices, but when accessing the primvar value, USD tells us that it's empty. `tmp.GetArraySize()` at [https://github.com/Autodesk/arnold-usd/blob/9b8ab2f8226b7f48e738c55cf07fec58b488bc97/translator/reader/prim_reader.cpp#L524] returns zero, resulting in an empty indices array. This causes the primvar translation code to skip the current primvar because indices end up empty.
