### ISSUE TITLE
Rendering the PointInstancedMedCity example file with usdView and arnold crashes

### ISSUE THREAD

**Issue by digicpictures** [Autodesk/arnold-usd#72]
**Describe the bug**
When I open the PointInstancedMedCity example file with usdView and choose Arnold as the renderer, then the whole usdView app crashes. It renders nicely with OGL and Embree.

**To Reproduce**
1. Open usdView with the PointInstancedMedCity.usd
2. Select Arnold from the Hydra renderers.
3. Watch usdView disappear.

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 19.11
 - Compiler: MSVC 2019
 - OS: Win 10

**Comment by sirpalee** [comment]
Hey @digicpictures, I tried this problem again on Windows 10, using USD 0.20.2 (but with VS 2017) and Arnold 5.4.0.2 and 6.0.2.0 and I wasn't able to reproduce the crash.

Since there were a lots of changes in how we handle point instances, could you please try it again?

**Comment by pierre-ed** [comment]
Hi everyone!
Sorry to barge in, but I ran the PointInstancedMedCity scene a couple of times and I am afraid the crash remains.

I've only managed to get a complete rendering with HdArnold (in usdview) once: with `HDARNOLD_threads=1`, in debug, with a debugger attached! In any other conditions (release, # threads > 1, or directly from a terminal), I immediately get a segfault (btw, I am under Linux and my environment does have the `LD_PRELOAD` variable properly set). 

For what it's worth, [here](https://github.com/Autodesk/arnold-usd/files/4226044/PointInstancedMedCity_callstack.log) is what looks like the most explicit callstack I got so far.

- Arnold : 6.0.1.0
- USD : 0.20.02
- OS : CentOS Linux release 7.6.1810

Cheers,
   Pierre.

**Comment by sirpalee** [comment]
Hey @pierre-ed thanks for the stack trace!

**Comment by sirpalee** [comment]
@pierre-ed rendering this file or any other instancing related was stable for me on Linux, but I think I was able to reproduce the crash on Windows.

Looking at your stack trace, nothing obvious, but I'm confused why HDARNOLD_threads affects your crash. Your crash seems to happen during sync, which is managed by Hydra and the HDARNOLD_threads variable should not affect it. What happens if you try using `PXR_WORK_THREAD_LIMIT=1`? That should disable the parallel sync of the USD/Hydra scene.

**Comment by sirpalee** [comment]
@pierre-ed I think I found what's going on. The crash is unrelated to the instancing. Looking at your stack trace, you can see the base `HdCamera` class being at the top. I think the problem is that the render delegate doesn't create it's own `HdArnoldCamera` type but use the built-in `HdCamera` and that's doing something nasty.

Can you try rendering with the following command? `usdview --renderer Arnold --mask /MediterraneanHills ./PointInstancedMedCity.usd`

I'll add a placeholder HdArnoldCamera class in the meantime, but it would be good to get confirmation from you that's the issue.

**Comment by pierre-ed** [comment]
Hi!
Sorry for the belated reply.

`usdview --renderer Arnold --mask /MediterraneanHills ./PointInstancedMedCity.usd` works beautifully, as well as switching to HdArnold with `PXR_WORK_THREAD_LIMIT=1 usdview ./PointInstancedMedCity.usd`. On the other hand, directly going with `usdview ./PointInstancedMedCity.usd` keeps on consistently crashing.

Thanks again for how reactive you guys are.
Cheers.

**Comment by sirpalee** [comment]
Hi @pierre-ed , thanks for testing it.

In the meantime I managed to track down two possible issues that causes this scene to crash. The issue was, both crashes happened randomly, based on threading, and both of the issues were pointing at two different locations in the source code.

One of them is a problem with SamplePrimvar, which seems to crash when PXR_WORK_THREAD_LIMIT is set to bigger than one or zero. This crash originates from USD itself, but I'm still looking into it.

The other problem is that usd_proc can cause a random crash, due to the statically linked TBB and USD combination (and neither libraries are supposed to be used as statically linked dependencies). 

Sadly, the the second problem requires a core update to fix. (though this doesn't affect 6.0.1.0, only 6.0.2.0)

**Comment by sirpalee** [comment]
Created two new issues that better represent the crashes we saw while investigating this ticket: #336 and #337 .
