### ISSUE TITLE
The procedural crashes when rendering an ass file with a missing relative USD file path

### ISSUE THREAD

**Issue by digicpictures** [Autodesk/arnold-usd#74]
**Describe the bug**
I was rendering one of the testsuit ass files that uses a relative usd file dir, but the render was launched from a different directory. And this is what I get:
--
Coding Error (secondary thread): in Open at line 992 of build\USD\pxr\usd\lib\usd\stage.cpp -- Invalid root layer
00:00:07   169MB ERROR   |   signal caught: error 80000003
--

**To Reproduce**
Just start a render from another dir.

**Expected behavior**
Perhaps a warning message.

**Used Software Versions**
 - Arnold: 5.4.0.2
 - USD: 0.19.11
 - Compiler: MSCVC 2019
 - OS: Win 10

**Comment by sebastienblor** [comment]
This error about an invalid root layer usually means that the "usd" resource folder isn't found next to the procedural. I'm doing a PR to ensure this folder is properly copied during the testsuite, but it sounds like you're kicking the .ass files here and not running the testsuite, right ?

**Comment by digicpictures** [comment]
I don't think its related to the resource folder, because when executing the same command using a full path to an usd file, it works. And executing the command inside the same directory with the usd file also works. So the only case that crashes for me is when using the command outside the usd file dir with the procedural trying to load the usd file from the same dir.

> you're kicking the .ass files here and not running the testsuite, right ? 
Yes, I found the issue when I was trying to kick the testsuit's ass from a different folder.

**Comment by BigRoy** [comment]
To be entirely clear, I think you're referring to [example this line in the `.ass` file](https://github.com/Autodesk/arnold-usd/blob/fc63ca2629edf3eecf04f2a9d57118b19729037b/testsuite/test_0005/data/test.ass#L73) that references the USD as a relative file, specifically `sphere.usd`.

However when initiating `kick` from another folder it cannot find the specific `sphere.usd` file, thus it fails to load. The expected behavior instead would be to display an error/warning that says, "USD file not found:" or something like that.

As such, the error described above is _not_ related to the USD file referring to a relative path inside it but about the `.ass` file defining a relative path for the `usd` procedural.

**Comment by digicpictures** [comment]
Yep, exactly.
