### ISSUE TITLE
Regression in animated xforms

### ISSUE THREAD

**Issue by sebastienblor** [Autodesk/arnold-usd#80]
**Describe the bug**
Since we adressed #51 , we now use a `UsdGeomXformCache` in order to get the world matrix of the geometries. But this now prevents animated xforms from being rendered properly

**To Reproduce**
Run `abuild test_0018`

**Comment by BigRoy** [comment]
Quickly looking at the commits surrounding that PR it seems the [`SetFrame` of the reader](https://github.com/Autodesk/arnold-usd/blob/fc63ca2629edf3eecf04f2a9d57118b19729037b/translator/reader/reader.cpp#L277) never gets triggered, and thus never refreshed. 

If that's the case, then adding in [`exportPrim`](https://github.com/Autodesk/arnold-usd/pull/52/files#diff-fb7810c2f523751955c8108454866911R74) or in [`getMatrix`](https://github.com/Autodesk/arnold-usd/pull/52/files#diff-7f2113e87cd73a9bf42beac4d0fd6e6fR36) should fix it.
```
reader.setFrame(time.frame);
```

That wouldn't be the correct way of fixing it since it would be slow... but at least we identify if the lack of setting the frame is the issue. If so, then we just need to identify where to best place that call so it only updates on time change. Likely that location would be somewhere [here](https://github.com/Autodesk/arnold-usd/blob/fc63ca2629edf3eecf04f2a9d57118b19729037b/translator/reader/utils.cpp#L82).

**Comment by sebastienblor** [comment]
Yes, calling `setFrame` is what I referred to as solution 3) in #81
