### ISSUE TITLE
no way to have pointInstancer prototypes hidden

### ISSUE THREAD

**Issue by dietchmatch** [Autodesk/arnold-usd#904]
https://github.com/Autodesk/arnold-usd/blob/a7f2fa4da9b70a9f5973ed1369193d73a6bcd0ee/translator/reader/read_geometry.cpp#L686

https://github.com/Autodesk/arnold-usd/blob/master/translator/reader/read_geometry.cpp#L747

there seems to be no way of having different behavior for the prototypes and the point-instanced instances.
should we have prototypes always invisible? should we have a new flag for hiding prototypes?

**Comment by dietchmatch** [comment]
looks like the prototypes get exported twice ... i compiled this myself with the following
![image](https://user-images.githubusercontent.com/48324989/140062179-dbf8904a-9226-4e7b-a53e-25c137a82979.png)
and still get the prototypes rendered

**Comment by dietchmatch** [comment]
and also, when rendering i get messagges like this
![image](https://user-images.githubusercontent.com/48324989/140062310-bf027097-7dae-41eb-a3bb-28cbfb41c397.png)
so i guess they're there twice

**Comment by sebastienblor** [comment]
Hi @dietchmatch , could you attach the usd file you're  trying to read ? Does this scene load as you'd expect in usdview (or hydra) but not when rendering it with the procedural ?
we have #458 about automatically hiding primitives under the point instancer, in order to match what usdview does, but I'm not sure you're talking about the same issue here

**Comment by sebastienblor** [comment]
Ok, I understand now. I think it's the same issue as #458 , so we could mark this ticket as duplicate. 
What we should do is : 
1) always hide the primitives under the point instancer hierarchy (not necessarily the prototypes, but in practice that's often the case)
2) For the instances visibilities, instead of considering the visibility of the point instancer prim for all instances, we should use the visibility of the prototype.

**Comment by dietchmatch** [comment]
thanks @sebastienblor
