### ISSUE TITLE
No tool named 'doxygen': not a Zip file

### ISSUE THREAD

**Issue by suesauer** [Autodesk/arnold-usd#91]
**Describe the bug**
While I try to compile it gets stuck on doxygen.

**To Reproduce**
1. Run scons in Linux terminal:
2. Get error:
"scons: Reading SConscript files ...
SConsEnvironmentError: No tool named 'doxygen': not a Zip file:
  File "/home/suesauer/Documents/ArnoldUSD/arnold-usd/SConstruct", line 104:
    env = Environment(variables = vars, ENV = os.environ, tools = ['default', 'doxygen'])
  File "/usr/lib64/python2.7/site-packages/scons/SCons/Environment.py", line 992:
    apply_tools(self, tools, toolpath)
  File "/usr/lib64/python2.7/site-packages/scons/SCons/Environment.py", line 107:
    env.Tool(tool)
  File "/usr/lib64/python2.7/site-packages/scons/SCons/Environment.py", line 1798:
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib64/python2.7/site-packages/scons/SCons/Tool/__init__.py", line 122:
    module = self._tool_module()
  File "/usr/lib64/python2.7/site-packages/scons/SCons/Tool/__init__.py", line 277:
    raise SCons.Errors.SConsEnvironmentError(m)
"

**Expected behavior**
Expect to be able to compile

**Screenshots**
![Screenshot from 2019-12-02 13-23-43](https://user-images.githubusercontent.com/58251706/69955752-13d67e80-1507-11ea-8889-488cda21ec3e.png)
doxygen location in repo:
![Screenshot from 2019-12-02 13-24-43](https://user-images.githubusercontent.com/58251706/69955801-2b156c00-1507-11ea-910d-09209f72afaa.png)
place in SConstruct where it gets stuck
![Screenshot from 2019-12-02 13-25-46](https://user-images.githubusercontent.com/58251706/69955885-5f892800-1507-11ea-8020-47b68b265627.png)

**Used Software Versions**
 - Arnold:  5.4.0.2
 - USD:  0.19.11
 - Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
 - OS: Linux Centos 7
 - Any 3rd-party app: Houdini

**Additional context**
Trying to compile this for the first time, tried https://bitbucket.org/russel/scons_doxygen/src/default/
this didn't work either.

Thanks Sue

**Comment by BigRoy** [comment]
Could you try and instead of running `scons` manually use the accompanying [`abuild` script](https://github.com/Autodesk/arnold-usd/blob/master/abuild). As you can see that will add some additional dependencies that are in this repository of which one I believe is [doxygen](https://github.com/Autodesk/arnold-usd/tree/master/tools/scons-custom/site_tools/doxygen).

**Comment by suesauer** [comment]
Thanks @BigRoy trying that now

**Comment by sirpalee** [comment]
@suesauer there are two ways to setup configuration values.

Either pass the configuration as command line arguments to abuild, like you are doing it now, or create a custom.py in the root of the repository and set your variables there. The preferred way is using abuild, instead of manually running scons, as there are a set of scons modules that are added to the environment automatically.

**Comment by suesauer** [comment]
Thanks @sirpalee will keep that in mind :D
