### ISSUE TITLE
Camera projections are not working in Hydra material networks

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#934]
**Describe the bug**
At the moment connecting camera nodes to UsdShade (to use for camera projection) nodes is not working.

We face several challenges:
- We need to be able to access the Arnold camera node pointer when translating shader networks.
- We have to deal with the multi-threaded sync nature of Hydra, so translating shaders needs to happen after translating cameras.
- Deleting cameras need to update shader networks where the camera pointer is used.

**Comment by johnhaddon** [comment]
This is something we're thinking about for Gaffer's (non-hydra) Arnold backend as well. I wonder if you've considered changing the `camera_projection` shader to make it easier instead? Perhaps if it took a `string` rather than a `NODE *` parameter, the shader itself could do an `AiNodeLookUpByName()` at the last minute in `node_update`?
